name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: (stencil-sass with Stencil version ${{ matrix.stencil_version }})
    strategy:
      fail-fast: false
      matrix:
        # Run with multiple different versions of Stencil in parallel:
        # 1. DEFAULT - uses the version of Stencil written in `pnpm-lock.yaml`, keeping the same version used by the
        # Stencil team as a source of truth
        # 2. 2 - will install the latest release under major version 2 of Stencil. This should be kept as long as this
        # library supports Stencil v2.Y.Z
        # 3. 3 - will install the latest release under major version 3 of Stencil. This should be kept as long as this
        # library supports Stencil v3.Y.Z
        # 4. 4 - will install the latest release under major version 4 of Stencil. This should be kept as long as this
        # library supports Stencil v4.Y.Z
        stencil_version: ['DEFAULT', '2', '3', '4']
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    
    - name: 📦 Enable Corepack (pnpm)
      run: corepack enable
      shell: bash

    - name: 🕸️ Get Core Dependencies
      uses: stenciljs/.github/actions/get-core-dependencies@main

    - name: 📝 Prettier Check
      run: pnpm run prettier.dry-run
      shell: bash

    - name: 📦 Install Stencil ${{matrix.stencil_version}}
      run: pnpm add --save-dev @stencil/core@${{matrix.stencil_version}}
      shell: bash
      if: ${{ matrix.stencil_version != 'DEFAULT' }}

    - name: 📊 Report Stencil Version
      run: pnpm ls @stencil/core
      shell: bash

    - name: 🏗️ Build
      run: pnpm run build
      shell: bash

    - name: 🧪 Test
      run: pnpm run test.ci
      shell: bash

